### PR TITLE
Update tld.json

### PR DESCRIPTION
**Pull request by randomfly**
Locally tested the whois server -- worked for me.

### CODE REVIEW

**Comment by weppos** [comment]
@randomfly where does this information come from? The official delegation page doesn't list this server.
https://www.iana.org/domains/root/db/xn--ses554g.html

**Comment by randomfly** [comment]
Hello !
IANA doesn't help much, but i found the server with the whois information
from xn--2br42up03c.xn--ses554g
Here is the complete WHOIS :

Domain Name: 刘雅宁.网址
Domain ID: 4a2d8a1d5dd00147038d37289a3ad3f1
WHOIS Server: whois.gtld.knet.cn
Referral URL: http://www.zdns.cn/
Updated Date: 2014-08-03T04:57:32Z
Creation Date: 2014-08-03T04:57:32Z
Registry Expiry Date: 2017-08-03T04:57:32Z
Sponsoring Registrar: 互联网域名系统北京市工程研究中心
Sponsoring Registrar IANA ID: 1723
Domain Status: ok (http://www.icann.org/epp#OK)
Statue Codes: For more information on Whois status codes, please visit
https://www.icann.org/resources/pages/epp-status-codes-2014-06-16-en
Registrant ID: wz_4080211490998
Registrant Name: 刘宇增强版
Registrant Organization:
Registrant Street: 北京中关村南三街
Registrant City: 未知
Registrant State/Province: 未知
Registrant Postal Code:
Registrant Country: CN
Registrant Phone: 010-58813333-7
Registrant Phone Ext:
Registrant Fax: 010-58812666-126
Registrant Fax Ext:
Registrant Email: nameinfo@knet.cn
Admin ID: wz_4080211490998
Admin Name: 刘宇增强版
Admin Organization:
Admin Street: 北京中关村南三街
Admin City: 未知
Admin State/Province: 未知
Admin Postal Code:
Admin Country: CN
Admin Phone: 010-58813333-7
Admin Phone Ext:
Admin Fax: 010-58812666-126
Admin Fax Ext:
Admin Email: nameinfo@knet.cn
Tech ID: wz_4080211490998
Tech Name: 刘宇增强版
Tech Organization:
Tech Street: 北京中关村南三街
Tech City: 未知
Tech State/Province: 未知
Tech Postal Code:
Tech Country: CN
Tech Phone: 010-58813333-7
Tech Phone Ext:
Tech Fax: 010-58812666-126
Tech Fax Ext:
Tech Email: nameinfo@knet.cn
Name Server: nswz1.knet.cn
Name Server: nswz2.knet.cn
DNSSEC: unsigned
>>> Last update of WHOIS database: 2014-12-24T04:09:55Z <<<

NOTICE: The expiration date displayed in this record is the date the
registrar's sponsorship of the domain name registration in the registry is
currently set to expire. This date does not necessarily reflect the expiration
date of the domain name registrant's agreement with the sponsoring
registrar.  Users may consult the sponsoring registrar's Whois database to
view the registrar's reported date of expiration for this registration.

TERMS OF USE: .网址(.xn--ses554g) Registry Operator， has collected this
information for the WHOIS database through an ICANN-Accredited
Registrar and do not guarantee its accuracy or completeness. This
information is provided to you only for lawful purposes， and under no
circumstances should be used: (1) to allow， enable， or otherwise
support the transmission of mass unsolicited， commercial advertising
or solicitations via direct mail， electronic mail， or by telephone;
(2) in contravention of any applicable data and privacy protection
acts; or (3) to enable high volume， automated， electronic processes
that apply to the registry (or its systems). Compilation， repackaging，
dissemination， or other use of the WHOIS database in its entirety， or
of a substantial portion thereof， is not allowed without .网址 registrys
prior written permission. .网址 registry reserves the right to modify or
change these conditions at any time without prior or subsequent
notification of any kind. By executing this query， in any manner
whatsoever， you agree to abide by these terms.



Here is the source :
http://www.tcpiputils.com/browse/domain/xn--2br42up03c.xn--ses554g

**Comment by weppos** [comment]
Ok, thanks, I'll check that. One more thing, the patch is wrong. You just replaced the value, however the key should be `host` and not `adapter`. :blush:

**Comment by randomfly** [comment]
Sorry about that, i'll note it for next timer. Cheers !

**Comment by weppos** [comment]
No problem. Do you have time to fix it?

**Comment by randomfly** [comment]
If you were talking about the adapter/host thingy, i had it corrected.
Really, i didn't do anything else.

**Comment by randomfly** [comment]
Hi there, i'm sorry i couldn't look over the project sooner but my work
caught me unaware.
Anyway, i've noticed that the build failed after my update. Here's the job
report : https://travis-ci.org/weppos/whois/jobs/46963399
According to it, the bundle install command failed due to i18n...

Do you have any idea what could have caused that ? Since i only modified
the json file, i doubt my updates are to blame.
Thanks.

**Comment by randomfly** [comment]
*Gem::InstallError: i18n requires Ruby version >= 1.9.3.*

This pretty much says it all, i've noticed you are using the ruby version
1.9.2.
Since i'm using a later version locally (2.1.3) that explains why I never
encountered that error myself so I believe upgrading the ruby version would
fix that issue.
I would gladly fix that if I knew how, but i'm not used to the Travis CI
platform and have no idea how to change it.

Hope it helps.

**Comment by weppos** [comment]
See #389

**Pull request closed without merging**
