### PR TITLE
Handle empty updated_on for whois.schlund.info.

### PR DESCRIPTION
**Pull request by alexaitken**
Another problem similar to #353

Solution:

Skip the date parsing for empty Updated Date for whois.schlund.info
@weppos

### CODE REVIEW

**Comment by weppos** [comment]
:+1:

**Comment by alexaitken** [comment]
Can you release a new version?  Thanks

**Comment by weppos** [comment]
Done! v3.5.9 is out.

**Comment by alexaitken** [comment]
:+1:

**Pull request merged**
