### PR TITLE
Safenames parser.

### PR DESCRIPTION
**Pull request by robholland**
Implements #384

### CODE REVIEW

**Comment by maccman** [comment]
@weppos look good?

**Comment by maccman** [comment]
@weppos the build test failure looks non deterministic.

**Comment by weppos** [comment]
It looks like another issue with 1.9.2. I'll probably kill support for that Ruby version, since most library dependencies are >= 1.9.3.

**Comment by maccman** [comment]
@weppos any progress on this? :)

**Comment by weppos** [comment]
I'll check it asap.

**Comment by maccman** [comment]
ping?

**Comment by weppos** [comment]
Sorry for taking so long. Great patch, thanks! :clap:

**Pull request merged**
