### PR TITLE
Added additional support for nic.br via whois.gtlds.nic.br

### PR DESCRIPTION
**Pull request by mahtin**
Added an adaptor for .BR and associated TLDs (.globo .bom .final .rio .uol).

### CODE REVIEW

**Comment by weppos** [comment]
@mahtin is there a specific requirement for a custom adapter?

**Comment by mahtin** [comment]
Yes and no. The ICANN 2012 gTLD model should have its own adaptor at some point. This PR came about based on conversations with the Brazilian nic.br folks. While this presently is somewhat of a noop, it stands as a reminder that unlike .com/.net/etc there's different whois responses from players like this.

**Comment by weppos** [comment]
How is this different than the standard adapter?
https://github.com/weppos/whois/blob/master/lib/whois/server/adapters/standard.rb

It seems the standard (note .com uses verisign adapter) would work here.

**Comment by weppos** [comment]
Closing as no follow up. Parsers have been moved to https://github.com/weppos/whois-parser/ in the meanwhile.

**Pull request closed without merging**
