### PR TITLE
cnnic.cn: update parser format

### PR DESCRIPTION
**Pull request by ledowong**
CNNIC parser update.

### CODE REVIEW

**Comment by weppos** [comment]
Please provide a corresponding spec and make sure the existing one doesn't fail.

**Comment by weppos** [comment]
Merged, thank you!

**Comment by ledowong** [comment]
It doesn't update in GEM version 3.6.1 yet?

**Comment by weppos** [comment]
No, it's currently in master. I can release a new patch version if you need it.

**Comment by ledowong** [comment]
i patched my own version, so not urgent, thx.

**Comment by weppos** [comment]
I released 3.6.2

**Pull request merged**
